name: Build binaries
on:
  push:
    tags:
      - 'build-binaries'
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            container: node:24-bullseye
          - os: macos-latest
            platform: macos
            npm_arch: universal
          - os: windows-latest
            platform: windows
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container || '' }}
    permissions:
      contents: read
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v4
      - name: 🔨 Setup node
        if: ${{ !matrix.container }}
        uses: actions/setup-node@v4
        with:
          node-version: '24.14.0'
      - name: 👷 Install
        run: npm ci
        env:
          npm_config_arch: ${{ matrix.npm_arch }}
      - name: 📦 Packing binaries
        shell: bash
        run: |
          mkdir -p dist
          cp node_modules/isolated-vm/build/Release/isolated_vm.node dist/
          cp node_modules/@screeps/driver/native/build/Release/native.node dist/

      - name: 📦️ Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.platform }}
          path: dist/