name: Build platform packages
on:
  push:
    tags:
      - 'build-package'
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            container: node:24-bullseye
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container || '' }}
    permissions:
      contents: read
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v6
      - name: 🔨 Setup node
        if: ${{ !matrix.container }}
        uses: actions/setup-node@v6
        with:
          node-version: '24.14.0'
      - name: 👷 Install
        run: npm ci
      - name: 🔨 Install additional dependencies
        shell: bash
        run: npm install $(node -p "Object.entries(require('./node_modules/@screeps/launcher/package.json').devDependencies).map(([k,v])=>k+'@'+v).join(' ')")
      - name: 🧹 Cleanup electron
        shell: bash
        run: rm -rf node_modules/electron
      - name: 📦️ Upload package
        uses: actions/upload-artifact@v7
        with:
          name: package-${{ matrix.platform }}
          path: node_modules/
          include-hidden-files: true
